#!/usr/bin/env groovy

def loginBash = '#!/bin/bash -l'
def cluster = [cpus: "20",
               mem: "120g",
               prefix: "/home/jenkins/software",
               modules_prefix: "/home/jenkins/software/modules/all",
               easybuild_path: "/home/jenkins/easybuild/modules/all"
]



stage('Build Stage') {
    node('mg2') {
        gitVars = checkout scm
        def rootDir = pwd()
        def workingDir = sh(returnStdout: true,
                script: 'echo $PWD').trim()
        def build_id = BUILD_NUMBER
        def branch = gitVars.GIT_BRANCH.trim()
        def prefix
        def softwareList
        def usePrefix = ""
        if (branch == "origin/master"){
            prefix = cluster.prefix
            softwareList = "Template"
        } else {
            prefix = "${workingDir}/software"
            sh("""mkdir -p ${prefix} || true""")
            sh("""git diff origin/master...HEAD --name-only --oneline --no-merges --diff-filter=ACMRTUXB |grep ^easybuild\\/easyconfigs\\/.*\\.eb\\\$ |awk '{print \"basename \"\$0}' > ${workingDir}/${build_id}""")
            softwareList="${workingDir}/${build_id}"
            usePrefix = "--use=${cluster.modules_prefix}"
        }
        sh ("""echo $softwareList""")
        sh ("""cat $softwareList""")
        command = "srun --partition=1d --cpus-per-task=$cluster.cpus --mem=$cluster.mem $workingDir/jenkins/production.sh --prefix=$prefix --list=$softwareList --robot=$workingDir/easybuild/easyconfigs --eb-path=${cluster.easybuild_path} --hide-deps $usePrefix"
        sh("""$command""")
    }
}
